version: "3"
services:
  node:
    container_name: "heroesfest-server"
    build:
      context: api/
    depends_on:
      - postgres
    links:
      - postgres
    ports:
      - "10000:10000"
    networks:
      - net
    command: "./bin/entrypoint.sh"
    restart: on-failure
  postgres:
    container_name: "postgresql"
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: docker
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./api/bin/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./public/ASISTENTES_AL_EVENTO_HEROES_FEST.csv:/var/lib/postgresql/data/ASISTENTES_AL_EVENTO_HEROES_FEST.csv
    networks:
      - net
networks:
  net:
